words = [
    "Neovim",
    "acwrite",
    "bufhidden",
    "buftype",
    "concealcursor",
    "conceallevel",
    "cursorline",
    "esc",
    "extmark",
    "extmark's",
    "fzf",
    "keymaps",
    "mkdir",
    "netrw",
    "nvim",
    "swapfile",
    "tabstop",
    "trimempty",
    "virt",
]
